[package]
name = "pixy-server"
version = "0.1.0"
edition = "2021"
description = "A web server implementation of the Pixy service"
authors = ["Natalia Maximo <iam@natalia.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.19"
tracing = { version = "0.1.37", features = ["async-await"] }
tracing-subscriber = "0.3.17"
pixy-core = { path = "../pixy-core" }
config = { version = "0.13.3", default-features = false }
serde = { version = "1.0.175", features = ["derive"] }
tokio = { version = "1.29.1", features = ["rt", "rt-multi-thread", "net", "tracing", "macros"], default-features = false }
