[workspace]
members = ["pixy-core", "pixy", "pixy-server", "healthcheck"]
resolver = "2"

[workspace.package]
version = "0.2.1"
authors = ["Natalia Maximo <iam@natalia.dev>"]

[profile.release]
strip = true
