[package]
name = "pixy-core"
version = "0.1.0"
edition = "2021"
authors = ["Natalia Maximo <iam@natalia.dev>"]
license = "MIT"
repository = "https://github.com/cryptaliagy/pixy"
readme = "../README.md"
description = "A core library for Pixy, implementing the SensorGateway and its Handlers"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
reqwest = { version = "0.11.18", default-features = false }
reqwest-middleware = "0.2.2"
reqwest-retry = "0.2.2"
tokio = { version = "1.29.1" }
tracing = { version = "0.1.37", features = ["log", "async-await"] }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
jsonschema = { version = "0.17.1", default-features = false, features = ["resolve-file"] }
serde_yaml = { version = "0.9.25"}
minijinja = { version = "1.0.5", default-features = false, features = ["macros"] }



[features]
default = ["rustls-tls"]

native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dev-dependencies]
httpmock = "0.6.8"
openssl = { version = "0.10", features = ["vendored"] }