name: release

on:
  push:
    branches: [main]
    paths:
      - "src"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Dockerfile"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Collect version from file
        run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the gnu debug container
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          target: debug-gnu
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:debug-gnu,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version }}.${{ github.run_number }}-gnu-debug

      - name: Push the gnu runner container
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          target: prod-gnu
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-gnu,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version }}.${{ github.run_number }}-gnu

      - name: Push the musl debug container
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          target: debug
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:debug,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version }}.${{ github.run_number }}-debug

      - name: Push the musl runner container
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          target: prod
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version }}.${{ github.run_number }}
